name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Or your preferred Node.js version
      - name: Install dependencies
        run: yarn
      - name: Run tests and collect coverage
        run: yarn test -- --coverage # Assuming "npm test" runs Jest
      - name: Upload coverage to Codecov (Optional)
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # If using Codecov
